### PR TITLE
Set RPATH to $ORIGIN

### LINKED ISSUE #2: RPATHs are wrong.
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Since the actual library is in `$PREFIX/targets/x86_64-linux/lib` the RPATH is set to `$ORIGIN/../../../lib`.

A fix for this is to reverse the links, i.e. make the actual library `$PREFIX/lib/libnvToolsExt.so.1.0.0` and make `$PREFIX/targets/x86_64-linux/lib/libnvToolsExt.so.1.0.0`  to be a symlink.

Having the wrong RPATH will lead to loading wrong libraries.

cc @peterbell10

### Installed packages

```shell
# packages in environment at /home/isuru/miniforge3/envs/nvtx:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
cuda-nvtx                 12.0.76              hcb278e6_0    conda-forge
cuda-version              12.0                 hffde075_2    conda-forge
libgcc-ng                 13.2.0               h807b86a_3    conda-forge
libgomp                   13.2.0               h807b86a_3    conda-forge
libstdcxx-ng              13.2.0               h7e041cc_3    conda-forge
```
```


### Environment info

```shell
active environment : nvtx
    active env location : /home/isuru/miniforge3/envs/nvtx
            shell level : 2
       user config file : /home/isuru/.condarc
 populated config files : /home/isuru/miniforge3/.condarc
                          /home/isuru/.condarc
          conda version : 23.10.0
    conda-build version : 3.27.0
         python version : 3.10.13.final.0
       virtual packages : __archspec=1=zen3
                          __glibc=2.35=0
                          __linux=6.2.0=0
                          __unix=0=0
       base environment : /home/isuru/miniforge3  (writable)
      conda av data dir : /home/isuru/miniforge3/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /home/isuru/miniforge3/pkgs
                          /home/isuru/.conda/pkgs
       envs directories : /home/isuru/miniforge3/envs
                          /home/isuru/.conda/envs
               platform : linux-64
             user-agent : conda/23.10.0 requests/2.31.0 CPython/3.10.13 Linux/6.2.0-36-generic ubuntu/22.04.3 glibc/2.35 solver/libmamba conda-libmamba-solver/23.11.0 libmambapy/1.5.3
                UID:GID : 1000:1000
             netrc file : /home/isuru/.netrc
           offline mode : False
```
```

### PR DESCRIPTION
**Pull request by adibbley**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Fixes #2

### CODE REVIEW

File: recipe/test-rpath.sh [hunk 1]
```diff
@@ -0,0 +1,15 @@
...
+[[ ${target_platform} == "linux-64" ]] && targetsDir="targets/x86_64-linux"
+[[ ${target_platform} == "linux-ppc64le" ]] && targetsDir="targets/ppc64le-linux"
+[[ ${target_platform} == "linux-aarch64" ]] && targetsDir="targets/sbsa-linux"
+
+for lib in `find ${PREFIX}/${targetsDir}/lib -type f`; do
+    [[ $lib =~ \.so ]] || continue
+
+    rpath=$(patchelf --print-rpath $lib)
+    echo "$lib rpath: $rpath"
+    [[ $rpath == "\$ORIGIN" ]] || exit 1
```
Comment (bdice) [inline recipe/test-rpath.sh:12]: Maybe track if there were any failures in a variable. Then you can print the results for all the libs first and `exit 1` after the loop if there were any problematic libraries.

Comment (adibbley) [reply recipe/test-rpath.sh]: Added here https://github.com/conda-forge/cuda-nvtx-feedstock/pull/5/commits/9eb076121dd746c03e67a681648eba8df2044837

**Comment by adibbley** [comment]
@conda-forge-admin, please rerender
